//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledEquipmentInfo
    {
        public int ID { get; set; }
        public int TypeEquipmentID { get; set; }
        public int IdentificationDataID { get; set; }
        public int PortTypeInfoID { get; set; }
        public int InstallationInfoID { get; set; }
        public string OtherInfo { get; set; }
    
        public virtual IdentificationData IdentificationData { get; set; }
        public virtual InstallationInfo InstallationInfo { get; set; }
        public virtual PortTypeInfo PortTypeInfo { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
    }
}
