//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallationInfo()
        {
            this.InstalledEquipmentInfoes = new HashSet<InstalledEquipmentInfo>();
        }
    
        public int ID { get; set; }
        public string Address { get; set; }
        public string PointConnection { get; set; }
        public string Сoordinates { get; set; }
        public string Date { get; set; }
        public string NumbersPhones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipmentInfo> InstalledEquipmentInfoes { get; set; }
    }
}
