//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class st2_Sadyrin_telecom1Entities1 : DbContext
    {
        public st2_Sadyrin_telecom1Entities1()
            : base("name=st2_Sadyrin_telecom1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorizations { get; set; }
        public virtual DbSet<IdentificationData> IdentificationDatas { get; set; }
        public virtual DbSet<InstallationInfo> InstallationInfoes { get; set; }
        public virtual DbSet<InstalledEquipmentInfo> InstalledEquipmentInfoes { get; set; }
        public virtual DbSet<PortTypeInfo> PortTypeInfoes { get; set; }
        public virtual DbSet<Subscruber> Subscrubers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeEquipment> TypeEquipments { get; set; }
    }
}
